name: Format

on:
    pull_request:
        paths:
            - "**.css"
            - "**.js"
            - "**.ts"
            - "**.vue"

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install
              run: npm ci

            - name: Run prettier
              run: npm run prettier --write 'src/**/*.{css,js,vue}'

            - uses: stefanzweifel/git-auto-commit-action@v3.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
