name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                node: [12.x, 14.x, 15.x]

        name: N${{ matrix.node }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm ci

            - name: Execute tests & Report coverage
              uses: paambaati/codeclimate-action@v2.5.5
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                  coverageCommand: npm run test
                  coverageLocations: ${{github.workspace}}/.coverage/lcov.info:lcov
